# Generated by Django 5.2.12 on 2026-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_incentives', '0004_alter_driverincentive_reward_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverincentive',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
