# Generated by Django 5.2.11 on 2026-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_riderstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('admin', 'Admin'), ('operator', 'Dashboard Operator')], default='rider', max_length=10),
        ),
    ]
