# Generated by Django 5.2.12 on 2026-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, default='', help_text='Expo push token for mobile notifications', max_length=255),
        ),
    ]
