# Generated by Django 5.2.12 on 2026-04-02 04:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_referral_code_user_referred_by_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RiderUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, help_text='google, facebook, apple, etc.', max_length=50, null=True),
        ),
    ]
