# Generated by Django 5.2.11 on 2026-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_arrived_at_ride_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='base_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
