# Generated by Django 5.2.11 on 2026-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_drop_address_ride_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], max_length=16, null=True),
        ),
    ]
