# Generated by Django 5.2.11 on 2026-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_base_fare_ride_distance_fare_ride_final_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final fare calculated at ride end', max_digits=8, null=True),
        ),
    ]
