# Generated by Django 5.2.11 on 2026-02-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_ride_final_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='candidate_driver_ids',
            field=models.JSONField(blank=True, default=list, help_text='Driver IDs matched during search attempts'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
