# Generated by Django 5.2.11 on 2026-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_ride_candidate_driver_ids_alter_ride_final_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='candidate_driver_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
