# Generated by Django 5.2.11 on 2026-02-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_ride_candidate_driver_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='cancellation_fee',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='candidate_driver_ids',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='distance_fare',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='no_show_marked_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='otp_verified_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='search_attempt',
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Searching'), ('ASSIGNED', 'Assigned'), ('ARRIVED', 'Arrived'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SEARCHING', max_length=32),
        ),
    ]
