# Generated by Django 5.2.11 on 2026-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_remove_ride_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver'), ('SYSTEM', 'System')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='no_show_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final fare locked at ride end', max_digits=8, null=True),
        ),
    ]
