# Generated by Django 5.2.11 on 2026-02-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_cancelled_at_ride_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='planned_distance_km',
            field=models.FloatField(blank=True, help_text='Planned distance from Google Directions', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='planned_duration_min',
            field=models.FloatField(blank=True, help_text='Planned duration from Google Directions', null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='planned_route_polyline',
            field=models.TextField(blank=True, help_text='Google Directions overview polyline', null=True),
        ),
    ]
