# Generated by Django 5.2.11 on 2026-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_ride_planned_distance_km_ride_planned_duration_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='actual_distance_km',
            field=models.FloatField(default=0.0, help_text='Distance actually driven (snapped to route)'),
        ),
        migrations.AddField(
            model_name='ride',
            name='last_snapped_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='last_snapped_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
