# Generated by Django 5.2.11 on 2026-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_ride_fare_breakdown_ride_is_fraud_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='city',
            field=models.CharField(db_index=True, default='Chennai', max_length=100),
        ),
    ]
