# Generated by Django 5.2.11 on 2026-02-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_ridefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, help_text='When rider successfully verified OTP', null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='actual_distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='final_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_duration_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
