# Generated by Django 5.2.11 on 2026-02-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_otp_verified_at_alter_ride_actual_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='candidate_driver_ids',
            field=models.JSONField(default=list, help_text='Ordered list of nearby driver IDs for matching'),
        ),
        migrations.AddField(
            model_name='ride',
            name='search_attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
