# Generated by Django 5.2.12 on 2026-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='actual_route_polyline',
            field=models.TextField(blank=True, default='', help_text='Encoded polyline of the actual path taken'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ride',
            name='planned_route_polyline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ridefeedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
