# Generated by Django 5.2.12 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_alter_ride_actual_route_polyline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver'), ('SYSTEM', 'System'), ('ADMIN', 'Admin')], default='', max_length=16),
        ),
    ]
