# Generated by Django 5.2.11 on 2026-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
