# Generated by Django 5.2.11 on 2026-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_bank_account_number_driver_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
