# Generated by Django 5.2.11 on 2026-02-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_total_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('completed_rides', models.PositiveIntegerField(default=0)),
                ('cancelled_rides', models.PositiveIntegerField(default=0)),
                ('no_shows', models.PositiveIntegerField(default=0)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.FloatField(default=5.0)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='drivers.driver')),
            ],
        ),
    ]
