# Generated by Django 5.2.11 on 2026-02-27 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driver_level_metrics_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverstats',
            name='last_active_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverstats',
            name='level_override_until',
            field=models.DateTimeField(blank=True, help_text='Manual level override expiry', null=True),
        ),
        migrations.AddField(
            model_name='driverstats',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
