# Generated by Django 5.2.12 on 2026-04-02 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_driver_bank_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverstats',
            name='driver',
            field=models.IntegerField(unique=True),
        ),
        migrations.RunSQL(
            sql="UPDATE drivers_driverstats SET driver = (SELECT user_id FROM drivers_driver WHERE id = drivers_driverstats.driver);",
            reverse_sql="UPDATE drivers_driverstats SET driver = (SELECT id FROM drivers_driver WHERE user_id = drivers_driverstats.driver);"
        ),
        migrations.AlterField(
            model_name='driverstats',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
