# Generated by Django 5.2.12 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
