# Generated by Django 5.2.12 on 2026-03-31 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_alter_ride_cancelled_by'),
        ('supports', '0005_alter_emergency_resolution_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=64),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='reason',
            field=models.CharField(blank=True, choices=[('OVERCHARGED', 'Overcharged'), ('DRIVER_MISCONDUCT', 'Driver Misconduct'), ('NO_SHOW_DISPUTE', 'No Show Dispute'), ('ROUTE_DEVIATION', 'Route Deviation'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='rides.ride'),
        ),
    ]
