# Generated by Django 5.2.11 on 2026-02-13 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=16)),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='payments_le_ride_id_ba738e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='payments_le_entry_t_d66fa1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgerentry',
            name='payments_le_created_8719a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_gateway_628fdd_idx',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('HOLD', 'Hold'), ('RELEASE', 'Release')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(blank=True, choices=[('PAYMENT', 'Payment'), ('DRIVER_EARNING', 'Driver Earning'), ('PLATFORM_COMMISSION', 'Platform Commission'), ('DRIVER_PAYOUT', 'Driver Payout'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('REFUND', 'Refund'), ('OTHER', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotency / correlation key', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='ride_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
