# Generated by Django 5.2.11 on 2026-02-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(db_index=True, default='razorpay', max_length=32)),
                ('event_id', models.CharField(help_text='Gateway webhook event id', max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Set once side-effects are applied', null=True)),
                ('status', models.CharField(default='RECEIVED', help_text='RECEIVED | PROCESSED | IGNORED | FAILED', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
