# Generated by Django 5.2.11 on 2026-02-06 04:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ledgerentry_remove_driverpayout_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(blank=True, help_text='Optional human readable reason', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='reference',
            field=models.CharField(help_text='payment:<id> | refund:<id> | adjustment:<id>', max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=24),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['created_at'], name='payments_le_created_8719a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CAPTURED')), fields=('ride_id',), name='one_captured_payment_per_ride'),
        ),
    ]
