# Generated by Django 5.2.11 on 2026-02-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='gateway_payout_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
