# Generated by Django 5.2.11 on 2026-02-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payout_gateway_payout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
