# Generated by Django 5.2.11 on 2026-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_ledgerentry_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
