# Generated by Django 5.2.12 on 2026-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_payout_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='reason',
            field=models.CharField(blank=True, choices=[('PAYMENT', 'Payment'), ('DRIVER_EARNING', 'Driver Earning'), ('PLATFORM_COMMISSION', 'Platform Commission'), ('DRIVER_PAYOUT', 'Driver Payout'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('REFUND', 'Refund'), ('PENALTY', 'Penalty'), ('INCENTIVE', 'Incentive'), ('CORRECTION', 'Correction'), ('OTHER', 'Other')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='payout',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
