# Generated by Django 5.2.11 on 2026-02-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="bonus_amount",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="driver_max_distance",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="driver_min_distance",
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.CharField(choices=[("RIDER", "Rider Offer")], max_length=10),
        ),
        migrations.DeleteModel(
            name="DriverIncentiveEarning",
        ),
    ]
