# Generated by Django 5.2.11 on 2026-02-27 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offer_bonus_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_value',
            new_name='max_discount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_discount_cap',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_distance',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_ride_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='total_usage_limit',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='usage_limit_per_user',
        ),
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_ride_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Total usage limit across all users', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('FLAT', 'Flat Amount'), ('PERCENTAGE', 'Percentage')], default='FLAT', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='total_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
