# Generated by Django 5.2.12 on 2026-03-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_code_alter_offer_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
